version: "3.9"

services:
  bot:
    build: .
    container_name: gastos-bot
    ports:
      - "10000:10000"
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS}
      SPREADSHEET_ID: ${SPREADSHEET_ID}
    volumes:
      - .:/app